"""Never answer a machine: auto-replies, bounces, mailing lists, bulk mail and our own mail.

Answering any of these risks a mail loop (two responders replying to each other forever) or
backscatter to an address that never wrote to us. Signals run from most to least certain.
"""

import re

from agent.models import InboundEmail

# Stamped on every message we send, so our own mail coming back (a forward rule, a
# redirect, a loop through another responder) is recognised no matter who relays it.
AGENT_MARKER_HEADER = "x-regulatory-agent"

_BULK_PRECEDENCE = frozenset({"bulk", "list", "junk", "auto_reply"})
_AUTORESPONDER_HEADERS = ("x-autoreply", "x-autorespond", "x-autogenerated")
_SUPPRESS_VALUES = frozenset({"all", "oof", "autoreply"})
_LIST_HEADERS = ("list-id", "list-unsubscribe")
# Includes notifications@: real people don't send from it, and it never reads replies.
_AUTOMATED_LOCAL_PART = re.compile(
    r"(?:mailer-daemon|postmaster|no[-_.]?reply|do[-_.]?not[-_.]?reply|bounces?|notifications?)"
    r"(?:[-+_.].*)?",
    re.IGNORECASE,
)
# Weak on its own (a person may write "out of office" in a subject), so it only counts for
# replies to one of our own messages.
_OUT_OF_OFFICE_SUBJECT = re.compile(
    r"out of (?:the )?office|away from (?:the )?office|automatic reply|auto[- ]?reply"
    r"|réponse automatique|abwesenheitsnotiz|automatische antwort|respuesta automática"
    r"|risposta automatica|automatisch antwoord",
    re.IGNORECASE,
)


def classify_automation(email: InboundEmail, *, own_address: str, return_path: str | None) -> str | None:
    """Why `email` must not be answered, or None if a person plausibly wrote it.

    `return_path` is the envelope sender from the topmost Return-Path (see
    `mime.envelope_sender`): "" or "<>" is the null sender, None means unknown.
    """
    headers = email.headers
    own_local, _, own_domain = own_address.lower().rpartition("@")
    from_local, _, from_domain = email.from_addr.rpartition("@")

    if AGENT_MARKER_HEADER in headers:
        return "carries our X-Regulatory-Agent marker (our own mail came back)"
    if from_domain == own_domain and from_local.split("+", 1)[0] == own_local:
        return "sent from our own address"

    auto_submitted = headers.get("auto-submitted", "").split(";", 1)[0].strip().lower()
    if auto_submitted and auto_submitted != "no":
        return f"Auto-Submitted: {auto_submitted}"
    precedence = headers.get("precedence", "").strip().lower()
    if precedence in _BULK_PRECEDENCE:
        return f"Precedence: {precedence}"
    for name in _AUTORESPONDER_HEADERS:
        if name in headers:
            return f"autoresponder header {name}"
    suppress = {value.strip().lower() for value in headers.get("x-auto-response-suppress", "").split(",")}
    if suppress & _SUPPRESS_VALUES:
        return f"X-Auto-Response-Suppress: {headers['x-auto-response-suppress']}"
    for name in _LIST_HEADERS:
        if name in headers:
            return f"mailing list or bulk sender ({name})"

    if return_path is not None and not return_path.strip("<> "):
        return "null envelope sender (bounce or delivery notification)"
    if headers.get("content-type", "").strip().lower().startswith("multipart/report"):
        return "multipart/report (delivery status or read receipt)"
    if _AUTOMATED_LOCAL_PART.fullmatch(from_local):
        return f"automated sender address {email.from_addr}"
    if _OUT_OF_OFFICE_SUBJECT.search(email.subject) and _replies_to_us(email, own_domain):
        return f"out-of-office reply to our message: {email.subject[:80]!r}"
    return None


def thread_root(email: InboundEmail) -> str:
    """Message-ID of the conversation's first message (per-thread caps key on this)."""
    if email.references:
        return email.references[0]
    return email.in_reply_to or email.message_id


def _replies_to_us(email: InboundEmail, own_domain: str) -> bool:
    return email.in_reply_to is not None and email.in_reply_to.lower().endswith(f"@{own_domain}>")
