from datetime import UTC, datetime

import pytest

from agent.mail.loops import classify_automation, in_thread_with_us, thread_root
from agent.mail.mime import parse_raw
from agent.models import InboundEmail

OWN = "agent@hsingh.app"


def email(
    *,
    from_addr: str = "jane@bank.example",
    subject: str = "Other Documents for M12205",
    headers: dict[str, str] | None = None,
    in_reply_to: str | None = None,
    references: tuple[str, ...] = (),
) -> InboundEmail:
    return InboundEmail(
        message_id="<m1@bank.example>",
        from_addr=from_addr,
        subject=subject,
        headers=headers or {},
        in_reply_to=in_reply_to,
        references=references,
        received_at=datetime(2026, 10, 4, tzinfo=UTC),
    )


def classify(message: InboundEmail, return_path: str | None = "jane@bank.example") -> str | None:
    return classify_automation(message, own_address=OWN, return_path=return_path)


def test_person_writing_to_us():
    assert classify(email(headers={"auto-submitted": "no", "precedence": "first-class"})) is None


@pytest.mark.parametrize(
    "headers",
    [
        {"x-regulatory-agent": "1"},
        {"auto-submitted": "auto-replied"},
        {"auto-submitted": "Auto-Generated; owner-email=it@bank.example"},
        {"precedence": "bulk"},
        {"precedence": " List "},
        {"precedence": "junk"},
        {"precedence": "auto_reply"},
        {"x-autoreply": "yes"},
        {"x-autorespond": "Vacation"},
        {"x-autogenerated": "Reply"},
        {"x-auto-response-suppress": "All"},
        {"x-auto-response-suppress": "DR, OOF"},
        {"x-auto-response-suppress": "AutoReply"},
        {"list-id": "Energy <energy.lists.example.org>"},
        {"list-unsubscribe": "<mailto:unsubscribe@esp.example>"},
        {"content-type": 'multipart/report; report-type=delivery-status; boundary="x"'},
        {"content-type": "Multipart/Report; report-type=disposition-notification"},
    ],
)
def test_automation_headers(headers):
    assert classify(email(headers=headers)) is not None


@pytest.mark.parametrize(
    "x_loop", ["agent@hsingh.app", "<Agent@HSINGH.app>", "lists@example.org, agent@hsingh.app"]
)
def test_x_loop_naming_us(x_loop):
    assert "X-Loop" in classify(email(headers={"x-loop": x_loop}))


def test_x_loop_naming_us_among_several_lines():
    raw = (
        b"From: jane@bank.example\r\nX-Loop: lists@example.org\r\nX-Loop: <agent@hsingh.app>\r\n"
        b"X-Loop: responder@example.net\r\nSubject: Other Documents for M12205\r\n\r\nM12205\r\n"
    )
    assert "X-Loop" in classify(parse_raw(raw, datetime(2026, 10, 4, tzinfo=UTC)))


@pytest.mark.parametrize(
    "x_loop",
    [
        "lists@example.org",
        "<responder@example.net>, lists@example.org",
        "other-agent@hsingh.app",
        "agent@hsingh.app.evil.example",
        "xagent@hsingh.app",
    ],
)
def test_unrelated_x_loop_is_not_a_signal(x_loop):
    assert classify(email(headers={"x-loop": x_loop})) is None


def test_suppress_values_for_other_reports_are_not_automation():
    assert classify(email(headers={"x-auto-response-suppress": "DR, RN, NRN"})) is None


@pytest.mark.parametrize("return_path", ["", "<>", " <> "])
def test_null_return_path(return_path):
    assert classify(email(), return_path=return_path) is not None


def test_unknown_return_path_is_not_a_signal():
    assert classify(email(), return_path=None) is None


@pytest.mark.parametrize(
    "sender",
    [
        "MAILER-DAEMON@mx.bank.example",
        "postmaster@bank.example",
        "noreply@bank.example",
        "no-reply@bank.example",
        "no_reply@bank.example",
        "donotreply@bank.example",
        "do-not-reply@bank.example",
        "bounce@esp.example",
        "bounces+12345@esp.example",
        "bounce-abc-123@esp.example",
        "notification@portal.example",
        "notifications@portal.example",
    ],
)
def test_automated_sender_addresses(sender):
    assert classify(email(from_addr=sender.lower())) is not None


@pytest.mark.parametrize(
    "sender", ["noreen@bank.example", "postmasters.guild@bank.example", "bouncer@club.example"]
)
def test_lookalike_local_parts_are_people(sender):
    assert classify(email(from_addr=sender)) is None


@pytest.mark.parametrize("sender", ["agent@hsingh.app", "agent+loop@hsingh.app"])
def test_our_own_address(sender):
    assert classify(email(from_addr=sender)) is not None


def test_other_mailboxes_on_our_domain_are_people():
    assert classify(email(from_addr="harpreet@hsingh.app")) is None


@pytest.mark.parametrize(
    "subject",
    [
        "Out of Office: Other Documents for M12205",
        "Automatic reply: Documents",
        "AutoReply: Documents",
        "Auto-Reply: Documents",
        "Réponse automatique : Documents",
        "Abwesenheitsnotiz: Re: Unterlagen",
        "Away from office until Monday",
        "Respuesta automática: Documents",
    ],
)
def test_out_of_office_subject_counts_only_for_replies_to_us(subject):
    assert classify(email(subject=subject, in_reply_to="<req-01J9@hsingh.app>")) is not None
    assert classify(email(subject=subject, in_reply_to="<CAx1@mail.gmail.com>")) is None
    assert classify(email(subject=subject)) is None


def test_thread_root():
    assert thread_root(email(references=("<a@x>", "<b@x>"), in_reply_to="<b@x>")) == "<a@x>"
    assert thread_root(email(in_reply_to="<b@x>")) == "<b@x>"
    assert thread_root(email()) == "<m1@bank.example>"


@pytest.mark.parametrize(
    ("in_reply_to", "references", "ours"),
    [
        ("<reply.0b6f3c1e-8d2a-4f7b-9c41-5e2d7a9b1c3f@hsingh.app>", (), True),
        # a reply to the person's own copy, threaded under our reply further up
        ("<m2@bank.example>", ("<m1@bank.example>", "<ack.0b6f3c1e-8d2a-4f7b-9c41-5e2d7a9b1c3f@HSINGH.APP>"), True),
        ("<m2@bank.example>", ("<m1@bank.example>",), False),
        (None, (), False),
        ("<x@hsingh.app.evil.example>", (), False),
    ],
)
def test_in_thread_with_us(in_reply_to, references, ours):
    assert in_thread_with_us(email(in_reply_to=in_reply_to, references=references), own_address=OWN) is ours
